#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


rm -f log.* 2>/dev/null
rm -rf processor*

runApplication decomposePar -force


runParallel sonicFoam


runApplication reconstructPar

#------------------------------------------------------------------------------
